//
//  Region.swift
//  Fivey (iOS)
//
//  Created by Joel Bernstein on 9/1/20.
//

import Foundation

enum Region
{
    static let displayName: [String] = [
        "United States",
        "United States",
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District of Columbia",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maine 1st District",
        "Maine 2nd District",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nebraska 1st District",
        "Nebraska 2nd District",
        "Nebraska 3rd District",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
    ]

    static let urlString: [String] = [
        "https://projects.fivethirtyeight.com/2020-election-forecast/us_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/us_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/alabama_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/alaska_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/arizona_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/arkansas_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/california_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/colorado_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/connecticut_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/delaware_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/district-of-columbia_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/florida_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/georgia_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/hawaii_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/idaho_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/illinois_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/indiana_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/iowa_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/kansas_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/kentucky_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/louisiana_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/maine_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/maine-1_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/maine-2_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/maryland_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/massachusetts_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/michigan_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/minnesota_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/mississippi_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/missouri_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/montana_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/nebraska_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/nebraska-1_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/nebraska-2_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/nebraska-3_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/nevada_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/new-hampshire_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/new-jersey_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/new-mexico_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/new-york_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/north-carolina_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/north-dakota_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/ohio_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/oklahoma_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/oregon_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/pennsylvania_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/rhode-island_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/south-carolina_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/south-dakota_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/tennessee_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/texas_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/utah_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/vermont_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/virginia_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/washington_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/west-virginia_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/wisconsin_timeseries.json",
        "https://projects.fivethirtyeight.com/2020-election-forecast/wyoming_timeseries.json",
    ]
}
